tag = "repo-issues"
auth_token= "Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
local_part= "issues"
domain= "example.tld"
base_url = "https://git.example.tld"
repo = "username/repo"
bot_name = "IssueBot"
bot_username = "username"
mailer = "cat"
log_file = "issue-bot.log"
